import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { type Story, type ReplicateModelTemplate } from "@shared/schema";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { ImageViewerDialog } from "@/components/image-viewer-dialog";
import { ImageHistoryDialog } from "@/components/image-history-dialog";
import { CustomInputModal } from "@/components/custom-input-modal";
import { ImageGenerationStatus } from "@/components/image-generation-status";
import { getCoreImageUrl, getPageImageUrl } from "@/utils/imageUrl";
import { PDFExport } from "@/components/pdf-export";
import { ChevronLeft, ChevronRight, Volume2, Bookmark, Share, Download, Edit, Save, BookOpen, Users, Clock, RefreshCw, Loader2, FileText, History, Settings } from "lucide-react";

interface StoryReaderProps {
  story: Story;
  onEdit?: () => void;
  onSave?: () => void;
}

export function StoryReader({ story, onEdit, onSave }: StoryReaderProps) {
  const [currentPageIndex, setCurrentPageIndex] = useState(0);
  const [customPrompt, setCustomPrompt] = useState("");
  const [overrideModelId, setOverrideModelId] = useState<string>("");
  const [isRegenerateDialogOpen, setIsRegenerateDialogOpen] = useState(false);
  const [isHistoryDialogOpen, setIsHistoryDialogOpen] = useState(false);
  const [zoomedImage, setZoomedImage] = useState<{ url: string; title: string } | null>(null);
  const [isCustomInputModalOpen, setIsCustomInputModalOpen] = useState(false);
  const [customInput, setCustomInput] = useState<Record<string, any> | null>(null);
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Query for user's saved templates for model override
  const { data: userTemplates = [] } = useQuery<ReplicateModelTemplate[]>({
    queryKey: ['/api/replicate/templates'],
    select: (data) => Array.isArray(data) ? data : [],
  });

  const bookmarkMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest("POST", `/api/stories/${story.id}/bookmark`);
      return response.json();
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['/api/stories', story.id] });
      queryClient.invalidateQueries({ queryKey: ['/api/stories'] });
      toast({
        title: story.isBookmarked ? "Bookmark Removed" : "Story Bookmarked!",
        description: story.isBookmarked ? "Story removed from bookmarks" : "Story added to your bookmarks",
      });
    },
    onError: (error) => {
      toast({
        title: "Bookmark Failed",
        description: error instanceof Error ? error.message : "Failed to update bookmark",
        variant: "destructive",
      });
    },
  });

  const handleBookmark = () => {
    bookmarkMutation.mutate();
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: story.title,
        text: `Check out this amazing children's story: ${story.title}`,
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(window.location.href);
      toast({
        title: "Link Copied!",
        description: "Story link has been copied to your clipboard",
      });
    }
  };

  const handleDownload = () => {
    // Create a simple text version of the story for download
    const storyText = [
      `${story.title}\n`,
      `Age Group: ${story.ageGroup}`,
      `Setting: ${story.setting}\n`,
      ...story.pages.map((page, index) => `Page ${index + 1}: ${page.text}`),
      `\nGenerated by StoryMaker AI`
    ].join('\n');

    const blob = new Blob([storyText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${story.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Download Started!",
      description: "Your story has been downloaded as a text file",
    });
  };
  
  const currentPage = story.pages[currentPageIndex];
  const isFirstPage = currentPageIndex === 0;
  const isLastPage = currentPageIndex === story.pages.length - 1;

  const nextPage = () => {
    if (!isLastPage) {
      setCurrentPageIndex(currentPageIndex + 1);
    }
  };

  const previousPage = () => {
    if (!isFirstPage) {
      setCurrentPageIndex(currentPageIndex - 1);
    }
  };

  const regenerateImageMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest("POST", `/api/stories/${story.id}/pages/${currentPage.pageNumber}/regenerate-image`, {
        customPrompt,
        overrideModelId: overrideModelId || undefined,
        customInput: customInput || undefined,
      });
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/stories/${story.id}`] });
      toast({
        title: "Image Regenerated!",
        description: "The page illustration has been updated with your custom prompt.",
      });
      setIsRegenerateDialogOpen(false);
      setCustomPrompt("");
      setOverrideModelId("");
      setCustomInput(null);
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to regenerate image",
        variant: "destructive",
      });
    },
  });

  return (
    <Card className="bg-white shadow-lg overflow-hidden">
      {/* Story Header */}
      <div className="bg-gradient-to-r from-indigo-600 to-pink-600 text-white p-4 sm:p-6 lg:p-8 text-center">
        <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold mb-2" data-testid="story-title">{story.title}</h2>
        <p className="text-base sm:text-lg lg:text-xl opacity-90">A magical adventure story</p>
        <div className="flex flex-col sm:flex-row justify-center space-y-2 sm:space-y-0 sm:space-x-6 mt-4 text-xs sm:text-sm">
          <span><BookOpen className="inline mr-1" size={14} />{story.totalPages} Pages</span>
          <span><Users className="inline mr-1" size={14} />Ages {story.ageGroup}</span>
          <span><Clock className="inline mr-1" size={14} />5 min read</span>
        </div>
      </div>

      {/* Story Navigation */}
      <div className="bg-gray-50 px-4 sm:px-6 lg:px-8 py-3 sm:py-4 border-b border-gray-200">
        <div className="flex flex-col sm:flex-row items-center justify-between space-y-3 sm:space-y-0">
          <div className="flex flex-wrap items-center gap-2 sm:gap-4">
            <Button
              variant="outline"
              onClick={previousPage}
              disabled={isFirstPage}
              size="sm"
              className="text-xs sm:text-sm"
              data-testid="button-previous"
            >
              <ChevronLeft className="mr-1 sm:mr-2 h-3 w-3 sm:h-4 sm:w-4" />
              <span className="hidden sm:inline">Previous</span>
              <span className="sm:hidden">←</span>
            </Button>
            <span className="text-gray-600 font-medium text-xs sm:text-sm">
              Page <span data-testid="current-page-number">{currentPageIndex + 1}</span> of <span data-testid="total-pages">{story.totalPages}</span>
            </span>
            <Button
              onClick={nextPage}
              disabled={isLastPage}
              size="sm"
              className="bg-indigo-600 hover:bg-indigo-700 text-xs sm:text-sm"
              data-testid="button-next"
            >
              <span className="hidden sm:inline">Next</span>
              <span className="sm:hidden">→</span>
              <ChevronRight className="ml-1 sm:ml-2 h-3 w-3 sm:h-4 sm:w-4" />
            </Button>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <Button variant="ghost" size="sm" data-testid="button-read-aloud">
              <Volume2 className="h-4 w-4" />
            </Button>
            {getPageImageUrl(currentPage) && (
              <>
                <Dialog open={isRegenerateDialogOpen} onOpenChange={setIsRegenerateDialogOpen}>
                  <DialogTrigger asChild>
                    <Button variant="ghost" size="sm" data-testid="button-regenerate-image">
                      <RefreshCw className="h-4 w-4" />
                    </Button>
                  </DialogTrigger>
                <DialogContent className="sm:max-w-[525px]">
                  <DialogHeader>
                    <DialogTitle>Regenerate Page Image</DialogTitle>
                  </DialogHeader>
                  <div className="space-y-4">
                    <div>
                      <Label className="text-sm font-medium text-gray-900">
                        Custom Image Prompt
                      </Label>
                      <Textarea
                        value={customPrompt}
                        onChange={(e) => setCustomPrompt(e.target.value)}
                        placeholder="Describe how you want this page to look. For example: 'Make the characters look happier', 'Add more colorful flowers in the background', 'Show the characters in a different pose'..."
                        className="min-h-[120px]"
                        data-testid="textarea-custom-prompt"
                      />
                      <p className="text-sm text-gray-500 mt-2">
                        Current page: "{currentPage.text.slice(0, 100)}..."
                      </p>
                    </div>

                    {userTemplates.length > 0 && (
                      <div>
                        <Label className="text-sm font-medium text-gray-900">
                          Override Model (Optional)
                        </Label>
                        <Select value={overrideModelId} onValueChange={setOverrideModelId}>
                          <SelectTrigger className="mt-2">
                            <SelectValue placeholder="Use default preferred model" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="">Use default preferred model</SelectItem>
                            {userTemplates.map((template) => (
                              <SelectItem key={template.modelId} value={template.modelId}>
                                <div className="flex items-center gap-2">
                                  <span>{template.modelName || template.modelId}</span>
                                  <Badge variant="outline" className="text-xs">{template.modelId}</Badge>
                                </div>
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <p className="text-sm text-gray-500 mt-1">
                          Override your default model preference for this regeneration
                        </p>
                        
                        {/* Customize button for non-default models */}
                        {overrideModelId && overrideModelId !== '' && (
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => setIsCustomInputModalOpen(true)}
                            className="mt-2"
                            data-testid="button-customize-model"
                          >
                            <Settings className="h-4 w-4 mr-2" />
                            Customize Model Input
                          </Button>
                        )}
                      </div>
                    )}
                    <div className="flex flex-wrap gap-2 justify-end">
                      <Button
                        variant="outline"
                        onClick={() => {
                          setIsRegenerateDialogOpen(false);
                          setCustomPrompt("");
                          setOverrideModelId("");
                        }}
                        data-testid="button-cancel-regenerate"
                      >
                        Cancel
                      </Button>
                      <Button
                        onClick={() => regenerateImageMutation.mutate()}
                        disabled={regenerateImageMutation.isPending || !customPrompt.trim()}
                        data-testid="button-confirm-regenerate"
                      >
                        {regenerateImageMutation.isPending ? (
                          <>
                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                            Regenerating...
                          </>
                        ) : (
                          <>
                            <RefreshCw className="mr-2 h-4 w-4" />
                            Regenerate Image
                          </>
                        )}
                      </Button>
                    </div>
                  </div>
                </DialogContent>
                </Dialog>
                
                {/* Image History Button */}
                {currentPage.imageHistory && currentPage.imageHistory.length > 1 && (
                  <Button 
                    variant="ghost" 
                    size="sm" 
                    onClick={() => setIsHistoryDialogOpen(true)}
                    data-testid="button-image-history"
                  >
                    <History className="h-4 w-4" />
                  </Button>
                )}
              </>
            )}
            <Button 
              variant="ghost" 
              size="sm" 
              onClick={handleBookmark}
              data-testid="button-bookmark"
            >
              <Bookmark 
                className={`h-4 w-4 ${story.isBookmarked ? 'fill-yellow-400 text-yellow-400' : ''}`} 
              />
            </Button>
            <Button 
              variant="ghost" 
              size="sm" 
              onClick={handleShare}
              data-testid="button-share"
            >
              <Share className="h-4 w-4" />
            </Button>
            <Button 
              variant="ghost" 
              size="sm" 
              onClick={handleDownload}
              data-testid="button-download"
            >
              <Download className="h-4 w-4" />
            </Button>
            <PDFExport 
              story={story} 
              className="p-2 h-9 w-9 bg-transparent hover:bg-accent" 
            />
          </div>
        </div>
      </div>

      {/* Real-time Image Generation Status */}
      <div className="px-8 pt-4 pb-0">
        <ImageGenerationStatus 
          storyId={story.id}
          onImageComplete={(imageFileId, pageNumber) => {
            // Refresh the story data to show the new image
            queryClient.invalidateQueries({ queryKey: ['/api/stories', story.id] });
          }}
        />
      </div>

      {/* Story Page Content */}
      <CardContent className="p-8">
        <div className="max-w-4xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
            {/* Story Image */}
            <div className="order-2 lg:order-1">
              {getPageImageUrl(currentPage) || getCoreImageUrl(story) ? (
                <div
                  className="cursor-pointer transform hover:scale-105 transition-transform"
                  onClick={() => setZoomedImage({ 
                    url: getPageImageUrl(currentPage) || getCoreImageUrl(story)!, 
                    title: getPageImageUrl(currentPage) ? `Page ${currentPage.pageNumber} Illustration` : `${story.title} Core Image`
                  })}
                  data-testid="page-image-container"
                >
                  <img 
                    key={currentPage?.imageFileId || story.coreImageFileId}
                    src={getPageImageUrl(currentPage) || getCoreImageUrl(story)}
                    alt={getPageImageUrl(currentPage) ? `Story illustration for page ${currentPage.pageNumber}` : `${story.title} core image`}
                    className="w-full rounded-xl shadow-lg"
                    data-testid="page-image"
                  />
                  {!getPageImageUrl(currentPage) && getCoreImageUrl(story) && (
                    <div className="mt-2 text-xs text-gray-500 text-center">
                      Core Image (Page image not generated)
                    </div>
                  )}
                </div>
              ) : (
                <div className="w-full h-64 bg-gray-200 rounded-xl flex items-center justify-center">
                  <p className="text-gray-500">No image available</p>
                </div>
              )}
            </div>

            {/* Story Text */}
            <div className="order-1 lg:order-2">
              <div className="prose prose-lg max-w-none">
                <p 
                  className="text-xl leading-relaxed text-gray-800"
                  data-testid="page-text"
                >
                  {currentPage?.text}
                </p>
              </div>
            </div>
          </div>
        </div>
      </CardContent>

      {/* Image Modal */}
      {zoomedImage && (
        <ImageViewerDialog
          isOpen={true}
          onClose={() => setZoomedImage(null)}
          imageUrl={zoomedImage.url}
          title={zoomedImage.title}
        />
      )}

      {/* Image History Dialog */}
      <ImageHistoryDialog
        open={isHistoryDialogOpen}
        onOpenChange={setIsHistoryDialogOpen}
        story={story}
        pageNumber={currentPage?.pageNumber || 1}
        imageHistory={currentPage?.imageHistory}
      />

      {/* Story Footer */}
      <div className="bg-gray-50 px-8 py-6 border-t border-gray-200">
        <div className="flex justify-between items-center">
          <div className="flex items-center space-x-4">
            {onEdit && (
              <Button
                onClick={onEdit}
                className="bg-amber-500 hover:bg-amber-600 text-white font-medium"
                data-testid="button-edit-story"
              >
                <Edit className="mr-2 h-4 w-4" />
                Edit Story
              </Button>
            )}
            {onSave && (
              <Button
                onClick={onSave}
                className="bg-emerald-600 hover:bg-emerald-700 text-white font-medium"
                data-testid="button-save-story"
              >
                <Save className="mr-2 h-4 w-4" />
                Save to Library
              </Button>
            )}
          </div>

          <div className="text-sm text-gray-600">
            Created with StoryMaker AI
          </div>
        </div>
      </div>
      
      {/* Custom Input Modal */}
      {overrideModelId && (
        <CustomInputModal
          open={isCustomInputModalOpen}
          onOpenChange={setIsCustomInputModalOpen}
          template={userTemplates.find(t => t.modelId === overrideModelId)!}
          story={story}
          onSubmit={(input) => {
            setCustomInput(input);
            setIsCustomInputModalOpen(false);
            toast({
              title: "Custom Input Applied",
              description: "Your custom model settings have been configured for this regeneration.",
            });
          }}
          title="Customize Page Regeneration"
        />
      )}
    </Card>
  );
}
